spring:
  application:
    name: LOGINSERVICE
  profiles:
    active: dev
server:
  port: ${PORT:0}

---
spring:
  config:
    activate:
      on-profile: dev
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}
---

spring:
  config:
    activate:
      on-profile: prod
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver/eureka
